import type { CreditCard } from "./types";

export const CARDS: CreditCard[] = [
  {
    id: "hdfc-regalia",
    name: "Regalia Gold",
    bank: "HDFC Bank",
    bankShort: "HDFC",
    network: "Visa",
    tier: "premium",
    annualFee: 2500,
    feeWaiverSpend: 400000,
    rewardRatePct: 1.33,
    bonusCategoryRatePct: 6.66,
    bonusCategoriesLabel: "Marks & Spencer, Reliance, Myntra, Nykaa",
    loungeVisitsDomestic: 12,
    loungeVisitsInternational: 6,
    loungeValuePerVisit: 1500,
    milestoneBenefitValue: 6000,
    milestoneBenefitLabel: "₹1,500 voucher every quarter on ₹1.5L spend",
    cardGradient: "from-[#1a1a1a] via-[#2a1f12] to-[#4a3415]",
    accent: "#d4a356",
    emblem: "REGALIA",
  },
  {
    id: "sbi-cashback",
    name: "Cashback Card",
    bank: "SBI Card",
    bankShort: "SBI",
    network: "Visa",
    tier: "mid",
    annualFee: 999,
    feeWaiverSpend: 200000,
    rewardRatePct: 1.0,
    bonusCategoryRatePct: 5.0,
    bonusCategoriesLabel: "All online spends",
    loungeVisitsDomestic: 0,
    loungeVisitsInternational: 0,
    loungeValuePerVisit: 0,
    milestoneBenefitValue: 0,
    milestoneBenefitLabel: "No milestone benefits",
    cardGradient: "from-[#0f1419] via-[#16243d] to-[#1d3d6b]",
    accent: "#5da8ff",
    emblem: "CASHBACK",
  },
  {
    id: "axis-atlas",
    name: "Atlas",
    bank: "Axis Bank",
    bankShort: "Axis",
    network: "Visa",
    tier: "premium",
    annualFee: 5000,
    feeWaiverSpend: 1500000,
    rewardRatePct: 2.0,
    bonusCategoryRatePct: 5.0,
    bonusCategoriesLabel: "Travel, hotels, airlines",
    loungeVisitsDomestic: 8,
    loungeVisitsInternational: 12,
    loungeValuePerVisit: 1800,
    milestoneBenefitValue: 12500,
    milestoneBenefitLabel: "Tier upgrades + bonus EDGE Miles",
    cardGradient: "from-[#0d0f1c] via-[#1a1f3a] to-[#3a2860]",
    accent: "#9b7bff",
    emblem: "ATLAS",
  },
  {
    id: "amex-platinum-travel",
    name: "Platinum Travel",
    bank: "American Express",
    bankShort: "Amex",
    network: "Amex",
    tier: "premium",
    annualFee: 5000,
    feeWaiverSpend: 190000,
    rewardRatePct: 1.0,
    bonusCategoryRatePct: 4.5,
    bonusCategoriesLabel: "Travel bookings via Amex Travel",
    loungeVisitsDomestic: 8,
    loungeVisitsInternational: 0,
    loungeValuePerVisit: 1500,
    milestoneBenefitValue: 22000,
    milestoneBenefitLabel: "Travel vouchers on ₹1.9L & ₹4L spend",
    cardGradient: "from-[#0a0a0a] via-[#1a1a1a] to-[#3d3d3d]",
    accent: "#c0c0c0",
    emblem: "PLATINUM",
  },
  {
    id: "icici-emeralde",
    name: "Emeralde Private Metal",
    bank: "ICICI Bank",
    bankShort: "ICICI",
    network: "Mastercard",
    tier: "super-premium",
    annualFee: 12499,
    feeWaiverSpend: 1500000,
    rewardRatePct: 3.33,
    bonusCategoryRatePct: 6.0,
    bonusCategoriesLabel: "All spends, unlimited",
    loungeVisitsDomestic: 999,
    loungeVisitsInternational: 24,
    loungeValuePerVisit: 2000,
    milestoneBenefitValue: 18000,
    milestoneBenefitLabel: "Taj Epicure + EazyDiner Prime + golf",
    cardGradient: "from-[#0a1f1a] via-[#0f3a2e] to-[#1f5d47]",
    accent: "#3ad8a4",
    emblem: "EMERALDE",
  },
  {
    id: "hdfc-millennia",
    name: "Millennia",
    bank: "HDFC Bank",
    bankShort: "HDFC",
    network: "Visa",
    tier: "entry",
    annualFee: 1000,
    feeWaiverSpend: 100000,
    rewardRatePct: 1.0,
    bonusCategoryRatePct: 5.0,
    bonusCategoriesLabel: "Amazon, Flipkart, Swiggy, Zomato, Myntra",
    loungeVisitsDomestic: 8,
    loungeVisitsInternational: 0,
    loungeValuePerVisit: 1200,
    milestoneBenefitValue: 1000,
    milestoneBenefitLabel: "₹1,000 voucher on ₹1L per quarter",
    cardGradient: "from-[#0e0e15] via-[#1c1c2e] to-[#2f2f55]",
    accent: "#8ea1ff",
    emblem: "MILLENNIA",
  },
];

export const TRAVEL_OPTIONS: {
  value: "rare" | "occasional" | "frequent";
  label: string;
  hint: string;
  loungeUtilization: number;
}[] = [
  {
    value: "rare",
    label: "Rare Traveler",
    hint: "0–2 trips a year",
    loungeUtilization: 0.15,
  },
  {
    value: "occasional",
    label: "Occasional",
    hint: "3–8 trips a year",
    loungeUtilization: 0.5,
  },
  {
    value: "frequent",
    label: "Frequent Flyer",
    hint: "9+ trips a year",
    loungeUtilization: 0.9,
  },
];
