export const card_meta_axis = {
  card_id: "axis-atlas",
  issuer: "Axis Bank",
  card_name: "Atlas Credit Card",
  annual_fee_inr: 5000,
  annual_fee_gst_incl: 5900,
  fee_waiver_threshold_inr: null,
  min_income_annual_inr: 900000,
  min_age: 21,
  max_age: 60,
  spend_unit_inr: 100,
  redemption_fee_inr: 0,
  point_expiry_years: 3,
  network: ["Visa"],
  forex_markup_pct: 3.5,
  forex_gst_pct: 4.13,
  is_active: true,
  effective_from: "2024-04-20",
  effective_to: null,
  notes: [
    "No annual fee waiver.",
    "EDGE Miles are different from EDGE Points.",
    "1 EDGE Mile = ₹1 on Travel EDGE portal.",
    "Excluded from rewards and milestones: gold/jewellery, rent, wallet loads, government payments, insurance, fuel, utilities.",
    "Card discontinued for new applicants in 2025 but existing cardholders retain benefits.",
  ],
  spend_tiers: [
    {
      tier: "silver",
      min_spend_inr: 0,
      max_spend_inr: 750000,
      description: "Default tier for annual eligible spend below ₹7.5L.",
    },
    {
      tier: "gold",
      min_spend_inr: 750000,
      max_spend_inr: 1500000,
      description: "Unlocked when annual eligible spend crosses ₹7.5L.",
    },
    {
      tier: "platinum",
      min_spend_inr: 1500000,
      max_spend_inr: null,
      description: "Unlocked when annual eligible spend exceeds ₹15L.",
    },
  ],
  most_rewarding_category: [
    "flights_travel_edge",
    "hotels_direct",
    "airlines_direct",
  ],
  least_rewarding_category: [
    "gold_jewellery",
    "rent",
    "wallet",
    "government",
    "insurance",
    "fuel",
    "utilities",
  ],
  invite_only: false,
};

export const card_rewards_rules_axis = [
  {
    card_id: "axis-atlas",
    category: "flights",
    earn_type: "accelerated",
    points_per_unit: 5,
    spend_unit_inr: 100,
    counts_toward_threshold: null,
    monthly_cap_spend_inr: 200000,
    spend_gate_type: "travel_cap_pool",
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "5 EDGE Miles per ₹100",
      "Shared ₹2L monthly travel cap with hotels and Travel EDGE",
      "Above ₹2L cumulative travel spend rate drops to 2x",
    ],
  },
  {
    card_id: "axis-atlas",
    category: "hotels",
    earn_type: "accelerated",
    points_per_unit: 5,
    spend_unit_inr: 100,
    counts_toward_threshold: null,
    monthly_cap_spend_inr: 200000,
    spend_gate_type: "travel_cap_pool",
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "5 EDGE Miles per ₹100",
      "Shared ₹2L monthly travel cap with flights and Travel EDGE portal",
    ],
  },
  {
    card_id: "axis-atlas",
    category: "travel_flights_edge",
    earn_type: "accelerated",
    points_per_unit: 5,
    spend_unit_inr: 100,
    counts_toward_threshold: null,
    monthly_cap_spend_inr: 200000,
    spend_gate_type: "travel_cap_pool",
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "5 EDGE Miles per ₹100",
      "Same ₹2L monthly travel cap pool shared with airlines and hotels",
    ],
  },
  {
    card_id: "axis-atlas",
    category: "travel_hotels_edge",
    earn_type: "accelerated",
    points_per_unit: 5,
    spend_unit_inr: 100,
    counts_toward_threshold: null,
    monthly_cap_spend_inr: 200000,
    spend_gate_type: "travel_cap_pool",
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: ["5 EDGE Miles per ₹100", "Same ₹2L monthly travel cap pool"],
  },
  {
    card_id: "axis-atlas",
    category: "dining",
    earn_type: "base",
    points_per_unit: 2,
    spend_unit_inr: 100,
    counts_toward_threshold: null,
    monthly_cap_spend_inr: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: ["2 EDGE Miles per ₹100"],
  },
  {
    card_id: "axis-atlas",
    category: "food_delivery",
    earn_type: "base",
    points_per_unit: 2,
    spend_unit_inr: 100,
    counts_toward_threshold: null,
    monthly_cap_spend_inr: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: ["2 EDGE Miles per ₹100"],
  },
  {
    card_id: "axis-atlas",
    category: "online_general",
    earn_type: "base",
    points_per_unit: 2,
    spend_unit_inr: 100,
    counts_toward_threshold: null,
    monthly_cap_spend_inr: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: ["2 EDGE Miles per ₹100"],
  },
  {
    card_id: "axis-atlas",
    category: "international_spend",
    earn_type: "base",
    points_per_unit: 2,
    spend_unit_inr: 100,
    counts_toward_threshold: null,
    monthly_cap_spend_inr: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: ["2 EDGE Miles per ₹100", "3.5% forex markup applies separately"],
  },
  {
    card_id: "axis-atlas",
    category: "jewellery",
    earn_type: "excluded",
    points_per_unit: 0,
    spend_unit_inr: 100,
    counts_toward_threshold: false,
    monthly_cap_spend_inr: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: false,
    spend_counted_fee_waiver: false,
    notes: [
      "Zero EDGE Miles",
      "Excluded from earn and milestone/tier calculation",
    ],
  },
  {
    card_id: "axis-atlas",
    category: "fuel",
    earn_type: "excluded",
    points_per_unit: 0,
    spend_unit_inr: 100,
    counts_toward_threshold: false,
    monthly_cap_spend_inr: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: false,
    spend_counted_fee_waiver: false,
    notes: [
      "Zero EDGE Miles",
      "Excluded from earn and milestone/tier calculation",
      "Fuel surcharge waiver may apply",
    ],
  },
];

export const card_redemption_axis = [
  {
    card_id: "axis-atlas",
    channel: "travel_portal",
    channel_description: "Axis Travel EDGE portal – flights & hotels",
    value_per_point_inr: 1,
    engine_default: true,
    min_redemption_pts: 500,
    annual_cap_points: 150000,
    notes: [
      "1 EDGE Mile = ₹1 exactly on Travel EDGE portal",
      "Annual cap of 1,50,000 EDGE Miles per customer ID",
    ],
  },
  {
    card_id: "axis-atlas",
    channel: "partner_transfer",
    channel_description: "Airline & hotel partner transfer",
    engine_default: false,
    min_redemption_pts: 500,
    transfer_ratio: {
      edge_miles: 1,
      partner_miles: 2,
    },
    partner_groups: [
      {
        group: "B",
        annual_cap_edge_miles: 120000,
        partners: [
          "Air India",
          "AirAsia",
          "ITC Hotels",
          "IHG Hotels",
          "Air France-KLM",
          "Qantas",
          "SpiceJet",
          "Vistara",
        ],
      },
      {
        group: "A",
        annual_cap_edge_miles: 30000,
        partners: [
          "Accor ALL",
          "Air Canada",
          "Ethiopian Airlines",
          "Etihad Airways",
          "Japan Airlines",
          "Qatar Airways",
          "Singapore Airlines",
          "Turkish Airlines",
          "Thai Airways",
          "United Airlines",
          "Wyndham Hotels",
        ],
      },
    ],
    notes: [
      "Default transfer ratio is 1 EDGE Mile = 2 partner miles",
      "Annual caps apply per partner group",
    ],
  },
  {
    card_id: "axis-atlas",
    channel: "partner_transfer",
    channel_description: "Marriott Bonvoy transfer",
    engine_default: false,
    min_redemption_pts: 500,
    transfer_ratio: {
      edge_miles: 2,
      partner_points: 1,
    },
    partner: "Marriott Bonvoy",
    notes: [
      "Exception to normal transfer rule",
      "2 EDGE Miles = 1 Marriott Bonvoy point",
    ],
  },
];

export const card_milestones_axis = [
  {
    card_id: "axis-atlas",
    period: "annual",
    spend_threshold_inr: 300000,
    reward_type: "points",
    reward_value_inr: 2500,
    reward_points: 2500,
    mutual_exclusivity_group: "atlas_milestone_tier1",
    cumulative_with: ["atlas_milestone_tier2", "atlas_milestone_tier3"],
    condition: "annual_fee_paid=TRUE",
    notes: [
      "2,500 EDGE Miles on ₹3L eligible spend",
      "Cumulative with higher tiers",
    ],
  },
  {
    card_id: "axis-atlas",
    period: "annual",
    spend_threshold_inr: 750000,
    reward_type: "points",
    reward_value_inr: 2500,
    reward_points: 2500,
    mutual_exclusivity_group: "atlas_milestone_tier2",
    cumulative_with: ["atlas_milestone_tier1", "atlas_milestone_tier3"],
    condition: "annual_fee_paid=TRUE",
    notes: [
      "Additional 2,500 EDGE Miles on ₹7.5L spend",
      "Triggers Gold tier membership",
    ],
  },
  {
    card_id: "axis-atlas",
    period: "annual",
    spend_threshold_inr: 1500000,
    reward_type: "points",
    reward_value_inr: 5000,
    reward_points: 5000,
    mutual_exclusivity_group: "atlas_milestone_tier3",
    cumulative_with: ["atlas_milestone_tier1", "atlas_milestone_tier2"],
    condition: "annual_fee_paid=TRUE",
    notes: [
      "Additional 5,000 EDGE Miles on ₹15L spend",
      "Total milestone across all tiers = 10,000 EDGE Miles",
      "Triggers Platinum tier membership",
    ],
  },
  {
    card_id: "axis-atlas",
    period: "annual",
    spend_threshold_inr: 0,
    reward_type: "points",
    reward_value_inr: 0,
    reward_points: 0,
    mutual_exclusivity_group: "atlas_renewal_silver",
    cumulative_with: [],
    condition: "annual_fee_paid=TRUE AND tier=silver",
    notes: [
      "Silver tier renewal benefit",
      "No EDGE Miles awarded",
      "Fee payment required to maintain card",
    ],
  },
  {
    card_id: "axis-atlas",
    period: "annual",
    spend_threshold_inr: 0,
    reward_type: "points",
    reward_value_inr: 2500,
    reward_points: 2500,
    mutual_exclusivity_group: "atlas_renewal_gold",
    cumulative_with: [],
    condition: "annual_fee_paid=TRUE AND tier=gold",
    notes: [
      "Gold tier renewal benefit",
      "2,500 EDGE Miles on paying annual fee",
    ],
  },
  {
    card_id: "axis-atlas",
    period: "annual",
    spend_threshold_inr: 0,
    reward_type: "points",
    reward_value_inr: 5000,
    reward_points: 5000,
    mutual_exclusivity_group: "atlas_renewal_platinum",
    cumulative_with: [],
    condition: "annual_fee_paid=TRUE AND tier=platinum",
    notes: [
      "Platinum tier renewal benefit",
      "5,000 EDGE Miles awarded",
      "Annual fee effectively offset",
    ],
  },
  {
    card_id: "axis-atlas",
    period: "joining",
    spend_threshold_inr: 0,
    reward_type: "points",
    reward_value_inr: 2500,
    reward_points: 2500,
    mutual_exclusivity_group: null,
    cumulative_with: [],
    condition: "first_txn_within_37_days",
    notes: [
      "Welcome benefit for cards sourced after 20 Apr 2024",
      "2,500 EDGE Miles awarded after first transaction",
      "First transaction must occur within 37 days of card setup",
    ],
  },
];
