export const card_reward_category = {
  flights: "flights",
  hotels: "hotels",
  travel_flights_edge: "travel_flights_edge",
  travel_hotels_edge: "travel_hotels_edge",
  dining: "dining",
  food_delivery: "food_delivery",
  online_general: "online_general",
  international_spend: "international_spend",
  jewellery: "jewellery",
  fuel: "fuel",
  groceries: "groceries",
  offline_general: "offline_general",
  insurance: "insurance",
  utilities: "utilities",
  travel_hotels_smartbuy: "travel_hotels_smartbuy",
  travel_flights_smartbuy: "travel_flights_smartbuy",
  vouchers_smartbuy: "vouchers_smartbuy",
  rent_app: "rent_app",
  education: "education",
  travel_miscellaneous: "travel_miscellaneous",
  travel_flights_ishop: "travel_flights_ishop",
  travel_hotels_ishop: "travel_hotels_ishop",
  travel_flights_idfc_app: "travel_flights_idfc_app",
  travel_hotels_idfc_app: "travel_hotels_idfc_app",
  rent: "rent",
};
