export const card_meta_regalia = {
  card_id: "hdfc-regalia-gold",
  issuer: "HDFC Bank",
  card_name: "Regalia Gold Credit Card",
  annual_fee_inr: 2500,
  annual_fee_gst_incl: 2950,
  fee_waiver_threshold_inr: 400000,
  min_income_annual_inr: 1200000,
  min_age: 21,
  max_age: 60,
  spend_unit_inr: 150,
  redemption_fee_inr: 0,
  point_expiry_years: 2,
  network: ["Visa", "Mastercard"],
  forex_markup_pct: 2.0,
  forex_gst_pct: 2.36,
  is_active: true,
  effective_from: "2024-01-01",
  effective_to: null,
  notes: [
    "Points expire 2 years from earn date.",
    "Fee waiver based on anniversary year spend.",
  ],
  most_rewarding_category: [
    "Flights_Smartbuy",
    "Hotels_Smartbuy",
    "Myntra",
    "Nykaa",
    "Marks & Spencer",
    "Reliance Digital",
  ],
  least_rewarding_category: [
    "fuel",
    "wallet_loads",
    "rent_app",
    "emi",
    "cash_advance",
    "fees",
  ],
  invite_only: false,
};

export const card_rewards_rules_regalia = [
  {
    card_id: "hdfc-regalia-gold",
    category: "dining",
    earn_type: "base",
    points_per_unit: 4,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-regalia-gold",
    category: "food_delivery",
    earn_type: "base",
    points_per_unit: 4,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-regalia-gold",
    category: "groceries",
    earn_type: "base",
    points_per_unit: 4,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-regalia-gold",
    category: "online_general",
    earn_type: "base",
    points_per_unit: 4,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-regalia-gold",
    category: "utilities",
    earn_type: "base",
    points_per_unit: 4,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-regalia-gold",
    category: "insurance",
    earn_type: "base",
    points_per_unit: 4,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-regalia-gold",
    category: "education",
    earn_type: "base",
    points_per_unit: 4,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-regalia-gold",
    category: "travel_miscellaneous",
    earn_type: "base",
    points_per_unit: 4,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-regalia-gold",
    category: "flights",
    earn_type: "base",
    points_per_unit: 4,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "Base 4x. SmartBuy portal gives additional bonus — see portal rows",
    ],
  },
  {
    card_id: "hdfc-regalia-gold",
    category: "hotels",
    earn_type: "base",
    points_per_unit: 4,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "Base 4x. SmartBuy portal gives additional bonus — see portal rows",
    ],
  },
  {
    card_id: "hdfc-regalia-gold",
    category: "offline_general",
    earn_type: "base",
    points_per_unit: 4,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-regalia-gold",
    category: "travel_flights_smartbuy",
    earn_type: "Accelerated_portal",
    points_per_unit: 20,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: 4000,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: ["Shared cap 4000 pts/month with hotels_smartbuy. 5x total."],
  },
  {
    card_id: "hdfc-regalia-gold",
    category: "travel_hotels_smartbuy",
    earn_type: "Accelerated_portal",
    points_per_unit: 40,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: 4000,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: ["Shared cap 4000 pts/month with flights_smartbuy. 10x total."],
  },
];

export const card_redemption_regalia = [
  {
    card_id: "hdfc-regalia-gold",
    channel: "gold_catalogue",
    channel_description: "Premium product catalogue (HDFC SmartBuy Rewards)",
    value_per_point_inr: 0.65,
    engine_default: true,
    min_redemption_pts: 2500,
    notes: ["Highest value. Use for customers who shop premium products."],
  },
  {
    card_id: "hdfc-regalia-gold",
    channel: "travel_portal",
    channel_description: "SmartBuy flights and hotels",
    value_per_point_inr: 0.5,
    engine_default: false,
    min_redemption_pts: 1500,
    notes: [
      "ENGINE DEFAULT. Used for comparison ranking. Best for travel customers.",
    ],
  },
  {
    card_id: "hdfc-regalia-gold",
    channel: "vouchers",
    channel_description: "Gift cards and merchant vouchers",
    value_per_point_inr: 0.35,
    engine_default: false,
    min_redemption_pts: 500,
    notes: ["Flipkart, Amazon, BigBasket vouchers."],
  },
  {
    card_id: "hdfc-regalia-gold",
    channel: "statement_credit",
    channel_description: "Cashback / statement credit",
    value_per_point_inr: 0.2,
    engine_default: false,
    min_redemption_pts: 500,
    notes: ["Lowest value. Avoid recommending for high-value customers."],
  },
  {
    card_id: "hdfc-regalia-gold",
    channel: "airmiles_air_india",
    channel_description: "Air India miles transfer",
    value_per_point_inr: 0.5,
    engine_default: false,
    min_redemption_pts: 1000,
    notes: ["1 RP = 1 Air India mile. Equiv ~₹0.50/point for business class."],
  },
];

export const card_milestones_regalia = [
  {
    card_id: "hdfc-regalia-gold",
    period: "quarterly",
    spend_threshold_inr: 150000,
    reward_type: "voucher",
    reward_value_inr: 1500,
    reward_points: null,
    mutual_exclusivity_group: "quarterly_milestone",
    cumulative_with: null,
    condition: null,
    notes: [
      "₹1,500 voucher: Marriott/Myntra/M&S/Reliance.",
      "Max 4x per year = ₹6,000.",
    ],
  },
  {
    card_id: "hdfc-regalia-gold",
    period: "annual",
    spend_threshold_inr: 500000,
    reward_type: "flight_voucher",
    reward_value_inr: 5000,
    reward_points: null,
    mutual_exclusivity_group: "annual_milestone_tier1",
    cumulative_with: "annual_milestone_tier2",
    condition: "annual_fee_paid=TRUE",
    notes: ["₹5,000 SmartBuy flight voucher.", "Tier 1 of 2."],
  },
  {
    card_id: "hdfc-regalia-gold",
    period: "annual",
    spend_threshold_inr: 750000,
    reward_type: "flight_voucher",
    reward_value_inr: 5000,
    reward_points: null,
    mutual_exclusivity_group: "annual_milestone_tier2",
    cumulative_with: "annual_milestone_tier1",
    condition: "annual_fee_paid=TRUE",
    notes: [
      "Additional ₹5,000 flight voucher.",
      "Tier 2 is cumulative with tier 1.",
      "Total possible = ₹10,000.",
    ],
  },
];
