export const card_meta_infinia = {
  card_id: "hdfc-infinia-metal",
  issuer: "HDFC Bank",
  card_name: "Infinia Credit Card Metal Edition",
  annual_fee_inr: 12500,
  annual_fee_gst_incl: 14750,
  fee_waiver_threshold_inr: 1000000,
  min_income_annual_inr: 3000000,
  min_age: 21,
  max_age: 60,
  spend_unit_inr: 150,
  redemption_fee_inr: 0,
  point_expiry_years: 3,
  network: ["Visa", "Mastercard"],
  forex_markup_pct: 2.0,
  forex_gst_pct: 2.36,
  is_active: true,
  effective_from: "2023-01-01",
  effective_to: null,
  invite_only: true,
  notes: [
    "Annual fee waiver on ₹10L eligible annual spend",
    "12,500 bonus reward points on joining and each renewal",
    "Base earn rate: 5 reward points per ₹150",
    "SmartBuy accelerated rewards: 10x multiplier",
    "SmartBuy bonus cap: 15,000 bonus reward points per day",
    "SmartBuy monthly bonus cap: 15,000 reward points shared across all SmartBuy categories",
    "Maximum reward points per statement cycle: 2,00,000",
    "Redemption cap: 1,50,000 reward points per month for flights, hotels and air miles",
    "Statement credit redemption cap: 50,000 reward points per month",
    "Utility reward points capped at 2,000 per month",
    "Insurance reward points capped at 5,000 per day",
    "Apple product purchases via SmartBuy limited to one per calendar quarter (effective Oct 2024)",
    "Tanishq vouchers limited to 50,000 reward points per quarter",
    "Global Value Program available for ₹199 + GST per year",
    "Global Value Program provides 1% cashback on international spends",
    "Global Value Program cashback capped at ₹1,000 per statement cycle",
    "No reward points on fuel transactions",
    "No reward points on rent or maintenance payments (effective Jan 2023)",
    "No reward points on wallet loads",
    "No reward points on EMI conversions",
    "No reward points on government or tax payments",
  ],
  most_rewarding_category: [
    "hotels_smartbuy",
    "flights_smartbuy",
    "vouchers_smartbuy",
    "apple_tanishq_smartbuy",
  ],
  least_rewarding_category: [
    "fuel",
    "rent",
    "wallet_loads",
    "emi",
    "government_tax",
    "cash_advance",
  ],
};

export const card_rewards_rules_infinia = [
  {
    card_id: "hdfc-infinia-metal",
    category: "dining",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-infinia-metal",
    category: "food_delivery",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-infinia-metal",
    category: "groceries",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-infinia-metal",
    category: "online_general",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-infinia-metal",
    category: "offline_general",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [],
  },
  {
    card_id: "hdfc-infinia-metal",
    category: "flights",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "Base earn 5 RP per ₹150",
      "SmartBuy accelerated rate available via flights_smartbuy",
    ],
  },
  {
    card_id: "hdfc-infinia-metal",
    category: "insurance",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: 5000,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: ["Daily cap 5,000 reward points on insurance spend"],
  },
  {
    card_id: "hdfc-infinia-metal",
    category: "utilities",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: 2000,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: ["Utility rewards capped at 2,000 reward points per month"],
  },
  {
    card_id: "hdfc-infinia-metal",
    category: "travel_hotels_smartbuy",
    earn_type: "accelerated_portal",
    points_per_unit: 50,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: 15000,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "10x accelerated earn rate",
      "Monthly bonus cap 15,000 RPs shared across all SmartBuy categories",
      "Daily SmartBuy bonus cap 15,000 reward points",
    ],
  },
  {
    card_id: "hdfc-infinia-metal",
    category: "travel_flights_smartbuy",
    earn_type: "accelerated_portal",
    points_per_unit: 25,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: 15000,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "5x accelerated earn rate",
      "Shared SmartBuy monthly bonus cap 15,000 reward points",
    ],
  },
  {
    card_id: "hdfc-infinia-metal",
    category: "vouchers_smartbuy",
    earn_type: "accelerated_portal",
    points_per_unit: 25,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: 15000,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "5x accelerated earn rate",
      "Includes Amazon, Flipkart, Swiggy, Zomato vouchers",
    ],
  },
  {
    card_id: "hdfc-infinia-metal",
    category: "fuel",
    earn_type: "zero",
    points_per_unit: 0,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "No reward points",
      "1% fuel surcharge waiver capped at ₹1,000 per billing cycle",
    ],
  },
  {
    card_id: "hdfc-infinia-metal",
    category: "rent_app",
    earn_type: "excluded",
    points_per_unit: 0,
    spend_unit_inr: 150,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_counted_milestone: false,
    spend_counted_fee_waiver: false,
    notes: [
      "No reward points",
      "1% fee on rent transactions via third-party apps",
    ],
  },
];

export const card_redemption_infinia = [
  {
    card_id: "hdfc-infinia-metal",
    channel: "travel_portal_smartbuy",
    channel_description: "Flights & hotel bookings via HDFC SmartBuy",
    value_per_point_inr: 1,
    engine_default: true,
    min_redemption_pts: 1000,
    monthly_cap_points: 150000,
    max_points_share_pct: 70,
    notes: [
      "1 RP = ₹1",
      "Maximum redemption 1,50,000 reward points per month for flights and hotels",
      "Up to 70% of booking value payable via reward points",
      "Remaining 30% paid by card which earns base reward points",
      "Best value redemption channel",
    ],
  },
  {
    card_id: "hdfc-infinia-metal",
    channel: "airmiles_1to1",
    channel_description: "Airline and hotel partner transfer",
    value_per_point_inr: 1,
    engine_default: false,
    min_redemption_pts: 1000,
    transfer_ratio: {
      reward_points: 1,
      partner_points: 1,
    },
    partners: [
      "Singapore Airlines KrisFlyer",
      "SpiceClub",
      "AirAsia Rewards",
      "Finnair Avios",
      "Flying Blue (Air France–KLM)",
      "Hainan Fortune Wings",
      "IHG One Rewards",
      "Vietnam Airlines LotusMiles",
      "Wyndham Rewards",
      "Cathay Pacific Asia Miles",
      "Thai Airways Royal Orchid Plus",
      "Qatar Airways Privilege Club",
      "Air India Flying Returns",
      "Radisson Rewards",
      "Marriott Bonvoy",
    ],
    notes: [
      "1 reward point transfers to 1 partner mile or point",
      "Air India Flying Returns added February 2025",
      "Actual redemption value depends on partner program and route",
    ],
  },
  {
    card_id: "hdfc-infinia-metal",
    channel: "airmiles_2to1",
    channel_description: "Airline and hotel partner transfer (reduced ratio)",
    value_per_point_inr: 0.5,
    engine_default: false,
    min_redemption_pts: 1000,
    transfer_ratio: {
      reward_points: 2,
      partner_points: 1,
    },
    partners: [
      "Club ITC Green Points",
      "Aeroplan",
      "ALL Accor Live Limitless",
      "Avianca LifeMiles",
      "British Airways Executive Club",
      "Etihad Guest",
      "Turkish Airlines Miles&Smiles",
      "United MileagePlus",
    ],
    notes: [
      "2 reward points convert to 1 partner point or mile",
      "These partners were downgraded from 1:1 transfer ratio in 2024",
    ],
  },
  {
    card_id: "hdfc-infinia-metal",
    channel: "apple_tanishq",
    channel_description: "Apple products or Tanishq vouchers via SmartBuy",
    value_per_point_inr: 1,
    engine_default: false,
    min_redemption_pts: 1000,
    max_points_share_pct: 70,
    notes: [
      "1 reward point = ₹1 value",
      "Only 70% of purchase value can be paid using reward points",
      "Maximum 1 Apple product per calendar quarter (effective October 2024)",
      "Tanishq vouchers capped at 50,000 reward points per quarter",
    ],
  },
  {
    card_id: "hdfc-infinia-metal",
    channel: "vouchers_products",
    channel_description: "Gift vouchers or products via SmartBuy or NetBanking",
    value_per_point_inr: 0.5,
    engine_default: false,
    min_redemption_pts: 500,
    notes: [
      "1 reward point = ₹0.50 value",
      "Includes Amazon, Flipkart, Croma, Reliance Smart, BigBasket, Blinkit and similar merchants",
    ],
  },
  {
    card_id: "hdfc-infinia-metal",
    channel: "statement_credit",
    channel_description: "Statement balance credit or cashback",
    value_per_point_inr: 0.3,
    engine_default: false,
    min_redemption_pts: 500,
    monthly_cap_points: 50000,
    notes: [
      "1 reward point = ₹0.30 value",
      "Worst redemption value",
      "Monthly redemption cap of 50,000 reward points",
      "Standard ₹50 redemption fee waived for Infinia cardholders",
    ],
  },
];

export const card_milestones_infinia = [
  {
    card_id: "hdfc-infinia-metal",
    period: "joining",
    spend_threshold_inr: 0,
    reward_type: "points",
    reward_value_inr: 12500,
    reward_points: 12500,
    mutual_exclusivity_group: null,
    cumulative_with: [],
    condition: "joining_fee_paid=TRUE",
    notes: [
      "12,500 bonus reward points credited after joining fee realization and card activation",
      "Value equals ₹12,500 when redeemed via SmartBuy travel portal",
      "Effectively offsets the joining fee if redeemed optimally",
    ],
  },
  {
    card_id: "hdfc-infinia-metal",
    period: "annual",
    spend_threshold_inr: 0,
    reward_type: "points",
    reward_value_inr: 12500,
    reward_points: 12500,
    mutual_exclusivity_group: "infinia_renewal_bonus",
    cumulative_with: [],
    condition: "annual_fee_paid=TRUE",
    notes: [
      "12,500 bonus reward points credited on renewal fee payment",
      "Equivalent to ₹12,500 value at SmartBuy travel redemption",
      "Effectively offsets the annual fee for users redeeming via travel portal",
    ],
  },
  {
    card_id: "hdfc-infinia-metal",
    period: "annual",
    spend_threshold_inr: 1000000,
    reward_type: "fee_waiver",
    reward_value_inr: 14750,
    reward_points: null,
    mutual_exclusivity_group: "infinia_fee_waiver",
    cumulative_with: [],
    condition: "annual_eligible_spend>=1000000",
    notes: [
      "Annual fee ₹12,500 plus GST (₹14,750 total) waived if eligible annual spend is ₹10,00,000 or more",
      "Eligible spend excludes fuel, EMI conversions, cash advances, rent via apps, wallet loads, and government or tax payments",
      "Applicable to Infinia Metal edition per official HDFC terms",
    ],
  },
];
