export const card_meta_emeralde = {
  card_id: "icici-emeralde-private-metal",
  issuer: "ICICI Bank",
  card_name: "Emeralde Private Metal Credit Card",
  annual_fee_inr: 12499,
  annual_fee_gst_incl: 14749,
  fee_waiver_threshold_inr: 1000000,
  min_income_annual_inr: null,
  min_age: 21,
  max_age: 65,
  spend_unit_inr: 200,
  redemption_fee_inr: 0,
  point_expiry_years: null,
  network: ["Mastercard"],
  forex_markup_pct: 2.0,
  forex_gst_pct: 2.36,
  is_active: true,
  effective_from: "2024-04-01",
  effective_to: null,
  invite_only: true,
  notes: [
    "Invite-only super premium metal credit card",
    "Base earn rate: 6 reward points per ₹200 spend (≈3% return)",
    "Category reward caps per billing cycle",
    "Groceries cap: 1000 reward points per cycle",
    "Utilities cap: 1000 reward points per cycle",
    "Education cap: 1000 reward points per cycle",
    "Insurance cap: 5000 reward points per cycle",
    "Excluded categories: fuel, rent (MCC 6513), tax payments, wallet loads",
    "1% fee on rent transactions",
    "Nil redemption fee",
    "Nil cash advance fee",
    "Nil late payment fee",
    "iShop portal accelerated rewards available",
    "Flights and vouchers earn 6x reward points on iShop portal",
    "Hotels earn 12x reward points on iShop portal",
    "iShop portal bonus cap: 18,000 reward points per month",
    "Air India Flying Returns transfer available at 1:1 ratio",
    "Annual fee waived if yearly spend exceeds ₹10,00,000",
    "Reward points lapse if the credit card is cancelled",
  ],
  most_rewarding_category: ["flights_ishop", "hotels_ishop", "vouchers_ishop"],
  least_rewarding_category: ["fuel", "rent", "tax", "wallet_loads"],
};

export const card_rewards_rules_emeralde = [
  {
    card_id: "icici-emeralde-private-metal",
    category: "dining",
    subcategory: "Restaurants / cafes",
    earn_type: "base",
    points_per_unit: 6,
    spend_unit_inr: 200,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: ["6 reward points per ₹200", "No category cap"],
  },
  {
    card_id: "icici-emeralde-private-metal",
    category: "food_delivery",
    subcategory: "Swiggy / Zomato delivery",
    earn_type: "base",
    points_per_unit: 6,
    spend_unit_inr: 200,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: ["6 reward points per ₹200", "No category cap"],
  },
  {
    card_id: "icici-emeralde-private-metal",
    category: "groceries",
    subcategory: "Supermarket / kiryana",
    earn_type: "base",
    points_per_unit: 6,
    spend_unit_inr: 200,
    counts_toward_threshold: null,
    monthly_cap_pts: 1000,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "6 reward points per ₹200",
      "Cap 1000 reward points per statement cycle",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    category: "utilities",
    subcategory: "Electricity / water / gas / telecom",
    earn_type: "base",
    points_per_unit: 6,
    spend_unit_inr: 200,
    counts_toward_threshold: null,
    monthly_cap_pts: 1000,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "6 reward points per ₹200",
      "Cap 1000 reward points per statement cycle",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    category: "education",
    subcategory: "School / college fees",
    earn_type: "base",
    points_per_unit: 6,
    spend_unit_inr: 200,
    counts_toward_threshold: null,
    monthly_cap_pts: 1000,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "6 reward points per ₹200",
      "Cap 1000 reward points per statement cycle",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    category: "insurance",
    subcategory: "Insurance premiums",
    earn_type: "base",
    points_per_unit: 6,
    spend_unit_inr: 200,
    counts_toward_threshold: null,
    monthly_cap_pts: 5000,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "6 reward points per ₹200",
      "Cap 5000 reward points per statement cycle",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    category: "travel_flights_ishop",
    subcategory: "Flights via ICICI iShop portal",
    earn_type: "accelerated_portal",
    points_per_unit: 36,
    spend_unit_inr: 200,
    counts_toward_threshold: null,
    monthly_cap_pts: 18000,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "6x base earn",
      "Shared monthly accelerated cap 18,000 reward points across iShop categories",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    category: "travel_hotels_ishop",
    subcategory: "Hotels via ICICI iShop portal",
    earn_type: "accelerated_portal",
    points_per_unit: 72,
    spend_unit_inr: 200,
    counts_toward_threshold: null,
    monthly_cap_pts: 18000,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "12x base earn",
      "Shared monthly accelerated cap 18,000 reward points",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    category: "vouchers_ishop",
    subcategory: "Vouchers via ICICI iShop",
    earn_type: "accelerated_portal",
    points_per_unit: 36,
    spend_unit_inr: 200,
    counts_toward_threshold: null,
    monthly_cap_pts: 18000,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: true,
    notes: [
      "6x base earn",
      "Shared monthly accelerated cap 18,000 reward points",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    category: "fuel",
    subcategory: "Fuel stations",
    earn_type: "excluded",
    points_per_unit: 0,
    spend_unit_inr: 200,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_counted_milestone: false,
    spend_counted_fee_waiver: false,
    notes: [
      "No reward points",
      "1% fuel surcharge waiver up to ₹1000 per cycle",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    category: "rent_app",
    subcategory: "Rent payments",
    earn_type: "excluded",
    points_per_unit: 0,
    spend_unit_inr: 200,
    counts_toward_threshold: null,
    monthly_cap_pts: null,
    spend_counted_milestone: false,
    spend_counted_fee_waiver: false,
    notes: ["No reward points", "1% fee charged on rent transactions"],
  },
];

export const card_redemption_emeralde = [
  {
    card_id: "icici-emeralde-private-metal",
    redemption_channel: "travel_portal",
    description: "Flights & hotels via ICICI iShop / reward portal",
    value_per_point_inr: 1.0,
    is_transfer_partner: true,
    engine_default: true,
    min_points_redeem: 2000,
    notes: [
      "1 reward point = ₹1 for flights or hotel bookings",
      "Nil redemption fee",
      "Highest practical value redemption channel",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    redemption_channel: "brand_vouchers",
    description: "Premium brand vouchers",
    value_per_point_inr: 1.0,
    is_transfer_partner: false,
    min_points_redeem: 1000,
    engine_default: false,
    notes: [
      "1 reward point = ₹1",
      "Premium brands include Apple, Tanishq, Coach, Jimmy Choo, Tumi etc.",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    redemption_channel: "general_catalogue",
    description: "General catalogue rewards",
    value_per_point_inr: 0.6,
    is_transfer_partner: false,
    engine_default: false,
    min_points_redeem: 1000,
    notes: [
      "1 reward point = ₹0.60",
      "Applies to products and experiences catalogue",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    redemption_channel: "statement_credit",
    description: "Statement credit or cashback",
    value_per_point_inr: 0.4,
    is_transfer_partner: false,
    min_points_redeem: 1000,
    engine_default: false,
    notes: ["1 reward point = ₹0.40", "Lowest value redemption option"],
  },
  {
    card_id: "icici-emeralde-private-metal",
    redemption_channel: "airmiles_air_india",
    description: "Air India frequent flyer miles transfer",
    value_per_point_inr: 0.5,
    is_transfer_partner: true,
    min_points_redeem: 2000,
    engine_default: false,
    notes: [
      "1 reward point = 1 Air India Flying Returns mile",
      "Approximate value ₹0.50 per mile depending on redemption",
      "Currently the only airline transfer partner",
    ],
  },
];

export const card_milestones_emeralde = [
  {
    card_id: "icici-emeralde-private-metal",
    benefit_type: "milestone",
    period: "annual",
    spend_threshold_inr: 400000,
    reward_type: "travel_voucher",
    reward_value_inr: 3000,
    points_awarded: null,
    voucher_partner: "EaseMyTrip",
    tier: "emeralde_milestone_tier1",
    replaces_tier: "emeralde_milestone_tier2",
    conditions: ["annual_fee_paid = TRUE"],
    notes: [
      "₹3,000 EaseMyTrip flight voucher on ₹4L annual spend",
      "Tier 1 of 2",
      "Mutually exclusive milestone — higher tier replaces this",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    benefit_type: "milestone",
    period: "annual",
    spend_threshold_inr: 800000,
    reward_type: "travel_voucher",
    reward_value_inr: 3000,
    points_awarded: null,
    voucher_partner: "EaseMyTrip",
    tier: "emeralde_milestone_tier2",
    replaces_tier: "emeralde_milestone_tier1",
    conditions: ["annual_fee_paid = TRUE"],
    notes: [
      "₹3,000 EaseMyTrip flight voucher on ₹8L annual spend",
      "Tier 2 of 2",
      "Replaces Tier 1 (not cumulative)",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    benefit_type: "welcome_bonus",
    period: "joining",
    spend_threshold_inr: 0,
    reward_type: "points",
    points_awarded: 12500,
    reward_value_inr: 12500,
    conditions: ["joining_fee_paid = TRUE"],
    notes: [
      "12,500 reward points on joining fee payment",
      "Joining fee ₹12,499",
      "Equivalent value ₹12,500 when redeemed at ₹1 per point via travel portal",
    ],
  },
  {
    card_id: "icici-emeralde-private-metal",
    benefit_type: "renewal_bonus",
    period: "annual",
    spend_threshold_inr: 0,
    reward_type: "points",
    points_awarded: 12500,
    reward_value_inr: 12500,
    conditions: ["annual_fee_paid = TRUE"],
    notes: [
      "12,500 reward points on renewal fee payment",
      "Effectively offsets annual fee when redeemed at ₹1 per point",
    ],
  },
];
