export const card_meta_mayura = {
  card_id: "idfc-mayura",
  issuer: "IDFC FIRST Bank",
  card_name: "Mayura Credit Card",
  annual_fee_inr: 5999,
  annual_fee_gst_incl: 7079,
  fee_waiver_threshold_inr: null,
  min_income_annual_inr: 2500000,
  min_age: 21,
  max_age: 60,
  spend_unit_inr: 150,
  redemption_fee_inr: 99,
  point_expiry_years: null,
  network: ["Visa Infinite", "RuPay Select"],
  forex_markup_pct: 0.0,
  forex_gst_pct: 0.0,
  is_active: true,
  effective_from: "2024-06-01",
  effective_to: null,
  notes: [
    "No fee waiver.",
    "Points never expire.",
    "RuPay variant earns rewards on UPI transactions.",
  ],
  most_rewarding_category: [
    "flights_idfc_app",
    "hotels_idfc_app",
    "monthly_spend_gt_40000",
  ],
  least_rewarding_category: [
    "fuel",
    "emi",
    "insurance",
    "utilities",
    "cash_advance",
    "below_min_txn",
  ],
  invite_only: false,
};

export const card_rewards_rules_mayura = [
  {
    card_id: "idfc-mayura",
    category: "dining",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: true,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: false,
    notes: [
      "5x below ₹20k threshold.",
      "10x above threshold.",
      "Straddle rule applies.",
    ],
  },
  {
    card_id: "idfc-mayura",
    category: "food_delivery",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: true,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: false,
    notes: ["Threshold-sensitive.", "Earns 5x to 10x."],
  },
  {
    card_id: "idfc-mayura",
    category: "groceries",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: true,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: false,
    notes: ["Threshold-sensitive."],
  },
  {
    card_id: "idfc-mayura",
    category: "online_general",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: true,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: false,
    notes: ["Threshold-sensitive."],
  },
  {
    card_id: "idfc-mayura",
    category: "flights",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: true,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: false,
    notes: ["Threshold-sensitive.", "Portal rows below for app-based booking."],
  },
  {
    card_id: "idfc-mayura",
    category: "hotels",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: true,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: false,
    notes: ["Threshold-sensitive.", "Portal rows below for app-based booking."],
  },
  {
    card_id: "idfc-mayura",
    category: "travel_miscellaneous",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: true,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: false,
    notes: ["Threshold-sensitive."],
  },
  {
    card_id: "idfc-mayura",
    category: "offline_general",
    earn_type: "base",
    points_per_unit: 5,
    spend_unit_inr: 150,
    counts_toward_threshold: true,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: false,
    notes: ["Threshold-sensitive."],
  },
  {
    card_id: "idfc-mayura",
    category: "travel_flights_idfc_app",
    earn_type: "portal",
    points_per_unit: 30,
    spend_unit_inr: 150,
    counts_toward_threshold: true,
    monthly_cap_pts: 25000,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: false,
    notes: [
      "30x total (additive with base).",
      "Monthly cap 25,000 bonus points shared with hotels.",
    ],
  },
  {
    card_id: "idfc-mayura",
    category: "travel_hotels_idfc_app",
    earn_type: "portal",
    points_per_unit: 50,
    spend_unit_inr: 150,
    counts_toward_threshold: true,
    monthly_cap_pts: 25000,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: false,
    notes: [
      "50x total (additive with base).",
      "Monthly cap 25,000 bonus points shared with flights.",
    ],
  },
  {
    card_id: "idfc-mayura",
    category: "rent",
    earn_type: "fixed",
    points_per_unit: 3,
    spend_unit_inr: 150,
    counts_toward_threshold: false,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: false,
    notes: ["Fixed 3x.", "Does not count toward ₹20k threshold."],
  },
  {
    card_id: "idfc-mayura",
    category: "education",
    earn_type: "fixed",
    points_per_unit: 3,
    spend_unit_inr: 150,
    counts_toward_threshold: false,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: false,
    notes: ["Fixed 3x.", "Does not count toward threshold."],
  },
  {
    card_id: "idfc-mayura",
    category: "fuel",
    earn_type: "zero",
    points_per_unit: 0,
    spend_unit_inr: 150,
    counts_toward_threshold: false,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: false,
    spend_counted_fee_waiver: false,
    notes: [
      "Zero points.",
      "Fuel surcharge waiver 1% capped at ₹500 per cycle.",
    ],
  },
  {
    card_id: "idfc-mayura",
    category: "below_min_txn",
    earn_type: "excluded",
    points_per_unit: 0,
    spend_unit_inr: 150,
    counts_toward_threshold: false,
    monthly_cap_pts: null,
    spend_gate_type: null,
    spend_gate_min_inr: null,
    spend_counted_milestone: true,
    spend_counted_fee_waiver: false,
    notes: ["No points earned on sub-₹150 transactions."],
  },
];

export const card_redemption_mayura = [
  {
    card_id: "idfc-mayura",
    channel: "travel_portal",
    channel_description: "IDFC Travel & Shop app (flights/hotels)",
    value_per_point_inr: 0.5,
    engine_default: true,
    min_redemption_pts: 1000,
    redemption_fee: {
      type: "flat",
      amount_inr: 99,
      gst_applicable: true,
      applies_per: "transaction",
    },
    notes: [
      "Engine default redemption channel.",
      "Best value redemption option.",
      "Redemption fee should be deducted from final redemption value.",
    ],
  },
  {
    card_id: "idfc-mayura",
    channel: "general_redemption",
    channel_description: "All other redemptions (vouchers/products)",
    value_per_point_inr: 0.25,
    engine_default: false,
    min_redemption_pts: 1000,
    redemption_fee: {
      type: "flat",
      amount_inr: 99,
      gst_applicable: true,
      applies_per: "transaction",
    },
    notes: [
      "Value is roughly half of travel portal redemption.",
      "Same redemption fee applies as travel portal.",
    ],
  },
];

export const card_milestones_mayura = [
  {
    card_id: "idfc-mayura",
    period: "annual",
    spend_threshold_inr: 800000,
    reward_type: "points",
    reward_value_inr: 1875,
    reward_points: 7500,
    mutual_exclusivity_group: "annual_milestone",
    cumulative_with: null,
    condition: "annual_fee_paid=TRUE",
    notes: [
      "7,500 points milestone reward.",
      "Worth ₹1,875 at ₹0.25 redemption value.",
      "Worth ₹3,750 if redeemed via travel portal.",
      "Tier 1 of 2.",
    ],
  },
  {
    card_id: "idfc-mayura",
    period: "annual",
    spend_threshold_inr: 1500000,
    reward_type: "points",
    reward_value_inr: 3750,
    reward_points: 15000,
    mutual_exclusivity_group: "annual_milestone",
    cumulative_with: null,
    condition: "annual_fee_paid=TRUE",
    notes: [
      "15,000 points milestone reward.",
      "Replaces Tier 1 reward.",
      "Mutually exclusive with Tier 1.",
      "Only the highest tier in the group is paid.",
    ],
  },
];
