const a = [
  {
    name: "YES Bank WELLNESS Credit Card",
    bankName: "YES Bank",
    category: "Wellness",
    slug: "yes-bank-wellness-credit-card-yes-bank",
  },
  {
    name: "YES Bank EMI Credit Card",
    bankName: "YES Bank",
    category: "EMI",
    slug: "yes-bank-emi-credit-card-yes-bank",
  },
  {
    name: "YES Bank KLICK RuPay Credit Card",
    bankName: "YES Bank",
    category: "UPI",
    slug: "yes-bank-klick-rupay-credit-card-yes-bank",
  },
  {
    name: "YES Bank UNI Credit Card",
    bankName: "YES Bank",
    category: "Digital",
    slug: "yes-bank-uni-credit-card-yes-bank",
  },
  {
    name: "YES Bank RIO Credit Card",
    bankName: "YES Bank",
    category: "Digital",
    slug: "yes-bank-rio-credit-card-yes-bank",
  },
  {
    name: "YES Bank FREO Credit Card",
    bankName: "YES Bank",
    category: "Digital",
    slug: "yes-bank-freo-credit-card-yes-bank",
  },
  {
    name: "YES Bank BYOC Credit Card",
    bankName: "YES Bank",
    category: "Flexible",
    slug: "yes-bank-byoc-credit-card-yes-bank",
  },
  {
    name: "FinBooster Credit Card",
    bankName: "YES Bank",
    category: "Co-branded",
    slug: "finbooster-credit-card-yes-bank",
  },
  {
    name: "YES PRIVATE Credit Card",
    bankName: "YES Bank",
    category: "Ultra Premium",
    slug: "yes-private-credit-card-yes-bank",
  },
  {
    name: "YES FIRST Preferred Credit Card",
    bankName: "YES Bank",
    category: "Premium",
    slug: "yes-first-preferred-credit-card-yes-bank",
  },
  {
    name: "YES PROSPERITY Edge Credit Card",
    bankName: "YES Bank",
    category: "Rewards",
    slug: "yes-prosperity-edge-credit-card-yes-bank",
  },
  {
    name: "YES PROSPERITY Rewards Credit Card",
    bankName: "YES Bank",
    category: "Rewards",
    slug: "yes-prosperity-rewards-credit-card-yes-bank",
  },
  {
    name: "YES PROSPERITY Cashback Credit Card",
    bankName: "YES Bank",
    category: "Cashback",
    slug: "yes-prosperity-cashback-credit-card-yes-bank",
  },
  {
    name: "YES PROSPERITY NRI Credit Card",
    bankName: "YES Bank",
    category: "NRI",
    slug: "yes-prosperity-nri-credit-card-yes-bank",
  },
  {
    name: "BOB ETERNA Credit Card",
    bankName: "Bank of Baroda",
    category: "Premium",
    slug: "bob-eterna-credit-card-bank-of-baroda",
  },
  {
    name: "BOB TIARA Credit Card",
    bankName: "Bank of Baroda",
    category: "Women",
    slug: "bob-tiara-credit-card-bank-of-baroda",
  },
  {
    name: "BOB PREMIER Credit Card",
    bankName: "Bank of Baroda",
    category: "Mid-range",
    slug: "bob-premier-credit-card-bank-of-baroda",
  },
  {
    name: "HPCL BOBCARD ENERGIE Credit Card",
    bankName: "Bank of Baroda",
    category: "Fuel",
    slug: "hpcl-bobcard-energie-credit-card-bank-of-baroda",
  },
  {
    name: "Uni GoldX BOBCARD Credit Card",
    bankName: "Bank of Baroda",
    category: "Co-branded",
    slug: "uni-goldx-bobcard-credit-card-bank-of-baroda",
  },
  {
    name: "PRAGATI Credit Card",
    bankName: "Bank of Baroda",
    category: "Secured",
    slug: "pragati-credit-card-bank-of-baroda",
  },
  {
    name: "BOB Corporate Credit Card",
    bankName: "Bank of Baroda",
    category: "Corporate",
    slug: "bob-corporate-credit-card-bank-of-baroda",
  },
  {
    name: "Nainital Bank RENAISSANCE Credit Card",
    bankName: "Bank of Baroda",
    category: "Co-branded",
    slug: "nainital-bank-renaissance-credit-card-bank-of-baroda",
  },
  {
    name: "BOB EMPOWER Credit Card",
    bankName: "Bank of Baroda",
    category: "Entry-level",
    slug: "bob-empower-credit-card-bank-of-baroda",
  },
  {
    name: "Snapdeal BOBCARD Credit Card",
    bankName: "Bank of Baroda",
    category: "Cashback",
    slug: "snapdeal-bobcard-credit-card-bank-of-baroda",
  },
  {
    name: "One BOBCARD Credit Card",
    bankName: "Bank of Baroda",
    category: "Digital",
    slug: "one-bobcard-credit-card-bank-of-baroda",
  },
  {
    name: "AU Bank Zenith Credit Card",
    bankName: "AU Bank",
    category: "Premium",
    slug: "au-bank-zenith-credit-card-au-bank",
  },
  {
    name: "AU Bank Vetta Credit Card",
    bankName: "AU Bank",
    category: "Mid-range",
    slug: "au-bank-vetta-credit-card-au-bank",
  },
  {
    name: "AU Bank Altura Plus Credit Card",
    bankName: "AU Bank",
    category: "Rewards",
    slug: "au-bank-altura-plus-credit-card-au-bank",
  },
  {
    name: "AU Bank Altura Credit Card",
    bankName: "AU Bank",
    category: "Entry-level",
    slug: "au-bank-altura-credit-card-au-bank",
  },
  {
    name: "AU Bank LIT Credit Card",
    bankName: "AU Bank",
    category: "Customizable",
    slug: "au-bank-lit-credit-card-au-bank",
  },
  {
    name: "AU Bank Xcite Credit Card",
    bankName: "AU Bank",
    category: "Entry-level",
    slug: "au-bank-xcite-credit-card-au-bank",
  },
  {
    name: "AU Bank Xcite Ace Credit Card",
    bankName: "AU Bank",
    category: "Rewards",
    slug: "au-bank-xcite-ace-credit-card-au-bank",
  },
  {
    name: "AU Bank Xcite Ultra Credit Card",
    bankName: "AU Bank",
    category: "Premium",
    slug: "au-bank-xcite-ultra-credit-card-au-bank",
  },
  {
    name: "AU Bank Xcite Edge Credit Card",
    bankName: "AU Bank",
    category: "Mid-range",
    slug: "au-bank-xcite-edge-credit-card-au-bank",
  },
  {
    name: "AU Bank Xcite Prime Credit Card",
    bankName: "AU Bank",
    category: "Premium",
    slug: "au-bank-xcite-prime-credit-card-au-bank",
  },
  {
    name: "OneCard Credit Card",
    bankName: "Multiple Issuers",
    category: "Metal / Fintech",
    slug: "onecard-credit-card-multiple-issuers",
  },
  {
    name: "Slice Credit Card",
    bankName: "North East Small Finance Bank",
    category: "BNPL / Fintech",
    slug: "slice-credit-card-north-east-small-finance-bank",
  },
  {
    name: "Uni Credit Card",
    bankName: "Yes Bank",
    category: "Fintech",
    slug: "uni-credit-card-yes-bank",
  },
  {
    name: "Scapia Federal Credit Card",
    bankName: "Federal Bank",
    category: "Travel",
    slug: "scapia-federal-credit-card-federal-bank",
  },
  {
    name: "YES Bank POP CLUB Credit Card",
    bankName: "Yes Bank",
    category: "Lifestyle",
    slug: "yes-bank-pop-club-credit-card-yes-bank",
  },
  {
    name: "SBM ZET Credit Card",
    bankName: "SBM Bank India",
    category: "Fintech",
    slug: "sbm-zet-credit-card-sbm-bank-india",
  },
  {
    name: "Edge CSB Bank RuPay Credit Card",
    bankName: "CSB Bank",
    category: "RuPay / Entry-level",
    slug: "edge-csb-bank-rupay-credit-card-csb-bank",
  },
  {
    name: "Gild Credit Card",
    bankName: "SBM Bank India",
    category: "Fintech",
    slug: "gild-credit-card-sbm-bank-india",
  },
  {
    name: "Uni Pay 1/3rd Credit Card",
    bankName: "SBM Bank India",
    category: "Pay Later / Fintech",
    slug: "uni-pay-1/3rd-credit-card-sbm-bank-india",
  },
  {
    name: "INFINIA Metal Edition Credit Card",
    bankName: "HDFC Bank",
    category: "Premium",
    slug: "infinia-metal-edition-credit-card-hdfc-bank",
  },
  {
    name: "Diners Club Black Credit Card",
    bankName: "HDFC Bank",
    category: "Premium",
    slug: "diners-club-black-credit-card-hdfc-bank",
  },
  {
    name: "Diners Club Metal Edition Credit Card",
    bankName: "HDFC Bank",
    category: "Premium",
    slug: "diners-club-metal-edition-credit-card-hdfc-bank",
  },
  {
    name: "Regalia Gold Credit Card",
    bankName: "HDFC Bank",
    category: "Premium",
    slug: "regalia-gold-credit-card-hdfc-bank",
  },
  {
    name: "Diners Club Privilege Credit Card",
    bankName: "HDFC Bank",
    category: "Mid-range",
    slug: "diners-club-privilege-credit-card-hdfc-bank",
  },
  {
    name: "Millennia Credit Card",
    bankName: "HDFC Bank",
    category: "Cashback",
    slug: "millennia-credit-card-hdfc-bank",
  },
  {
    name: "MoneyBack Plus Credit Card",
    bankName: "HDFC Bank",
    category: "Cashback",
    slug: "moneyback-plus-credit-card-hdfc-bank",
  },
  {
    name: "Freedom Credit Card",
    bankName: "HDFC Bank",
    category: "Entry-level",
    slug: "freedom-credit-card-hdfc-bank",
  },
  {
    name: "MoneyBack Credit Card",
    bankName: "HDFC Bank",
    category: "Entry-level",
    slug: "moneyback-credit-card-hdfc-bank",
  },
  {
    name: "Times Titanium Credit Card",
    bankName: "HDFC Bank",
    category: "Co-branded",
    slug: "times-titanium-credit-card-hdfc-bank",
  },
  {
    name: "6E Rewards XL – IndiGo HDFC Bank Credit Card",
    bankName: "HDFC Bank",
    category: "Airline",
    slug: "6e-rewards-xl-–-indigo-hdfc-bank-credit-card-hdfc-bank",
  },
  {
    name: "6E Rewards – IndiGo HDFC Bank Credit Card",
    bankName: "HDFC Bank",
    category: "Airline",
    slug: "6e-rewards-–-indigo-hdfc-bank-credit-card-hdfc-bank",
  },
  {
    name: "Marriott Bonvoy HDFC Bank Credit Card",
    bankName: "HDFC Bank",
    category: "Hotel",
    slug: "marriott-bonvoy-hdfc-bank-credit-card-hdfc-bank",
  },
  {
    name: "IndianOil HDFC Bank Credit Card",
    bankName: "HDFC Bank",
    category: "Fuel",
    slug: "indianoil-hdfc-bank-credit-card-hdfc-bank",
  },
  {
    name: "IRCTC HDFC Bank Credit Card",
    bankName: "HDFC Bank",
    category: "Travel",
    slug: "irctc-hdfc-bank-credit-card-hdfc-bank",
  },
  {
    name: "Tata Neu Infinity HDFC Bank Credit Card",
    bankName: "HDFC Bank",
    category: "Co-branded",
    slug: "tata-neu-infinity-hdfc-bank-credit-card-hdfc-bank",
  },
  {
    name: "Tata Neu Plus HDFC Bank Credit Card",
    bankName: "HDFC Bank",
    category: "Co-branded",
    slug: "tata-neu-plus-hdfc-bank-credit-card-hdfc-bank",
  },
  {
    name: "PIXEL Play Credit Card",
    bankName: "HDFC Bank",
    category: "Digital",
    slug: "pixel-play-credit-card-hdfc-bank",
  },
  {
    name: "PIXEL Go Credit Card",
    bankName: "HDFC Bank",
    category: "Digital",
    slug: "pixel-go-credit-card-hdfc-bank",
  },
  {
    name: "HDFC Bank UPI RuPay Credit Card",
    bankName: "HDFC Bank",
    category: "UPI",
    slug: "hdfc-bank-upi-rupay-credit-card-hdfc-bank",
  },
  {
    name: "H.O.G Diners Club Credit Card",
    bankName: "HDFC Bank",
    category: "Lifestyle",
    slug: "h.o.g-diners-club-credit-card-hdfc-bank",
  },
  {
    name: "Harley-Davidson Diners Club Credit Card",
    bankName: "HDFC Bank",
    category: "Lifestyle",
    slug: "harley-davidson-diners-club-credit-card-hdfc-bank",
  },
  {
    name: "Emeralde Private Metal Credit Card",
    bankName: "ICICI Bank",
    category: "Ultra Premium",
    slug: "emeralde-private-metal-credit-card-icici-bank",
  },
  {
    name: "Emeralde Credit Card",
    bankName: "ICICI Bank",
    category: "Premium",
    slug: "emeralde-credit-card-icici-bank",
  },
  {
    name: "Sapphiro Credit Card",
    bankName: "ICICI Bank",
    category: "Premium",
    slug: "sapphiro-credit-card-icici-bank",
  },
  {
    name: "Rubyx Credit Card",
    bankName: "ICICI Bank",
    category: "Mid-range",
    slug: "rubyx-credit-card-icici-bank",
  },
  {
    name: "Coral Credit Card",
    bankName: "ICICI Bank",
    category: "Entry-level",
    slug: "coral-credit-card-icici-bank",
  },
  {
    name: "Amazon Pay ICICI Bank Credit Card",
    bankName: "ICICI Bank",
    category: "Cashback",
    slug: "amazon-pay-icici-bank-credit-card-icici-bank",
  },
  {
    name: "MakeMyTrip ICICI Bank Signature Credit Card",
    bankName: "ICICI Bank",
    category: "Travel",
    slug: "makemytrip-icici-bank-signature-credit-card-icici-bank",
  },
  {
    name: "MakeMyTrip ICICI Bank Platinum Credit Card",
    bankName: "ICICI Bank",
    category: "Travel",
    slug: "makemytrip-icici-bank-platinum-credit-card-icici-bank",
  },
  {
    name: "Manchester United Signature Credit Card",
    bankName: "ICICI Bank",
    category: "Co-branded",
    slug: "manchester-united-signature-credit-card-icici-bank",
  },
  {
    name: "Manchester United Platinum Credit Card",
    bankName: "ICICI Bank",
    category: "Co-branded",
    slug: "manchester-united-platinum-credit-card-icici-bank",
  },
  {
    name: "Emirates Skywards ICICI Bank Emeralde Credit Card",
    bankName: "ICICI Bank",
    category: "Airline",
    slug: "emirates-skywards-icici-bank-emeralde-credit-card-icici-bank",
  },
  {
    name: "Emirates Skywards ICICI Bank Sapphiro Credit Card",
    bankName: "ICICI Bank",
    category: "Airline",
    slug: "emirates-skywards-icici-bank-sapphiro-credit-card-icici-bank",
  },
  {
    name: "Emirates Skywards ICICI Bank Rubyx Credit Card",
    bankName: "ICICI Bank",
    category: "Airline",
    slug: "emirates-skywards-icici-bank-rubyx-credit-card-icici-bank",
  },
  {
    name: "Vistara Infinite Credit Card",
    bankName: "ICICI Bank",
    category: "Airline",
    slug: "vistara-infinite-credit-card-icici-bank",
  },
  {
    name: "Vistara Signature Credit Card",
    bankName: "ICICI Bank",
    category: "Airline",
    slug: "vistara-signature-credit-card-icici-bank",
  },
  {
    name: "Vistara Platinum Credit Card",
    bankName: "ICICI Bank",
    category: "Airline",
    slug: "vistara-platinum-credit-card-icici-bank",
  },
  {
    name: "Etihad Guest Premier Credit Card",
    bankName: "ICICI Bank",
    category: "Airline",
    slug: "etihad-guest-premier-credit-card-icici-bank",
  },
  {
    name: "Etihad Guest Signature Credit Card",
    bankName: "ICICI Bank",
    category: "Airline",
    slug: "etihad-guest-signature-credit-card-icici-bank",
  },
  {
    name: "Emirates Skywards Coral Credit Card",
    bankName: "ICICI Bank",
    category: "Airline",
    slug: "emirates-skywards-coral-credit-card-icici-bank",
  },
  {
    name: "HPCL Super Saver Credit Card",
    bankName: "ICICI Bank",
    category: "Fuel",
    slug: "hpcl-super-saver-credit-card-icici-bank",
  },
  {
    name: "HPCL Coral American Express Credit Card",
    bankName: "ICICI Bank",
    category: "Fuel",
    slug: "hpcl-coral-american-express-credit-card-icici-bank",
  },
  {
    name: "HPCL Coral Visa/Mastercard Credit Card",
    bankName: "ICICI Bank",
    category: "Fuel",
    slug: "hpcl-coral-visa/mastercard-credit-card-icici-bank",
  },
  {
    name: "Platinum Chip Credit Card",
    bankName: "ICICI Bank",
    category: "Entry-level",
    slug: "platinum-chip-credit-card-icici-bank",
  },
  {
    name: "Expressions Credit Card",
    bankName: "ICICI Bank",
    category: "Lifestyle",
    slug: "expressions-credit-card-icici-bank",
  },
  {
    name: "Parakram Select Credit Card",
    bankName: "ICICI Bank",
    category: "Defence",
    slug: "parakram-select-credit-card-icici-bank",
  },
  {
    name: "Times Black Credit Card",
    bankName: "ICICI Bank",
    category: "Premium",
    slug: "times-black-credit-card-icici-bank",
  },
  {
    name: "Adani One Signature Credit Card",
    bankName: "ICICI Bank",
    category: "Travel",
    slug: "adani-one-signature-credit-card-icici-bank",
  },
  {
    name: "Adani One Platinum Credit Card",
    bankName: "ICICI Bank",
    category: "Travel",
    slug: "adani-one-platinum-credit-card-icici-bank",
  },
  {
    name: "IDFC FIRST ePay Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Digital",
    slug: "idfc-first-epay-credit-card-idfc-first-bank",
  },
  {
    name: "Kotak White Reserve Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Ultra Premium",
    slug: "kotak-white-reserve-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak White Signature Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Premium",
    slug: "kotak-white-signature-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Privy League Signature Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Premium",
    slug: "kotak-privy-league-signature-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Privy League Platinum Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Mid-range",
    slug: "kotak-privy-league-platinum-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Royale Signature Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Premium",
    slug: "kotak-royale-signature-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Essentia Platinum Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Cashback",
    slug: "kotak-essentia-platinum-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak League Platinum Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Mid-range",
    slug: "kotak-league-platinum-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Mojo Platinum Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Lifestyle",
    slug: "kotak-mojo-platinum-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Solaris Platinum Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Lifestyle",
    slug: "kotak-solaris-platinum-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak 811 Dream Different Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Digital",
    slug: "kotak-811-dream-different-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Urbane Gold Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Entry-level",
    slug: "kotak-urbane-gold-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Fortune Gold Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Entry-level",
    slug: "kotak-fortune-gold-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Delight Platinum Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Rewards",
    slug: "kotak-delight-platinum-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak NRI Royale Signature Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "NRI",
    slug: "kotak-nri-royale-signature-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Silk Inspire Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Women",
    slug: "kotak-silk-inspire-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak PVR Gold Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Entertainment",
    slug: "kotak-pvr-gold-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak PVR Platinum Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Entertainment",
    slug: "kotak-pvr-platinum-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak PVR Privy League Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Entertainment",
    slug: "kotak-pvr-privy-league-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Metro Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Travel",
    slug: "kotak-metro-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak BPCL Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Fuel",
    slug: "kotak-bpcl-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Corporate Wealth Signature Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Corporate",
    slug: "kotak-corporate-wealth-signature-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Solitaire Business Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Business",
    slug: "kotak-solitaire-business-credit-card-kotak-mahindra-bank",
  },
  {
    name: "Kotak Corporate Gold Credit Card",
    bankName: "Kotak Mahindra Bank",
    category: "Corporate",
    slug: "kotak-corporate-gold-credit-card-kotak-mahindra-bank",
  },
  {
    name: "RBL Bank Insignia Preferred Banking World Credit Card",
    bankName: "RBL Bank",
    category: "Ultra Premium",
    slug: "rbl-bank-insignia-preferred-banking-world-credit-card-rbl-bank",
  },
  {
    name: "RBL Bank World Safari Credit Card",
    bankName: "RBL Bank",
    category: "Travel",
    slug: "rbl-bank-world-safari-credit-card-rbl-bank",
  },
  {
    name: "RBL Bank ICON Credit Card",
    bankName: "RBL Bank",
    category: "Premium",
    slug: "rbl-bank-icon-credit-card-rbl-bank",
  },
  {
    name: "RBL Bank ShopRite Credit Card",
    bankName: "RBL Bank",
    category: "Rewards",
    slug: "rbl-bank-shoprite-credit-card-rbl-bank",
  },
  {
    name: "RBL Bank Platinum Delight Credit Card",
    bankName: "RBL Bank",
    category: "Lifestyle",
    slug: "rbl-bank-platinum-delight-credit-card-rbl-bank",
  },
  {
    name: "RBL Bank Platinum Maxima Plus Credit Card",
    bankName: "RBL Bank",
    category: "Rewards",
    slug: "rbl-bank-platinum-maxima-plus-credit-card-rbl-bank",
  },
  {
    name: "RBL Bank Cookies Credit Card",
    bankName: "RBL Bank",
    category: "Lifestyle",
    slug: "rbl-bank-cookies-credit-card-rbl-bank",
  },
  {
    name: "RBL Bank Play Credit Card",
    bankName: "RBL Bank",
    category: "Lifestyle",
    slug: "rbl-bank-play-credit-card-rbl-bank",
  },
  {
    name: "IRCTC RBL Bank RuPay Credit Card",
    bankName: "RBL Bank",
    category: "Travel",
    slug: "irctc-rbl-bank-rupay-credit-card-rbl-bank",
  },
  {
    name: "IndianOil RBL Bank Credit Card",
    bankName: "RBL Bank",
    category: "Fuel",
    slug: "indianoil-rbl-bank-credit-card-rbl-bank",
  },
  {
    name: "IndianOil RBL Bank Xtra Credit Card",
    bankName: "RBL Bank",
    category: "Fuel",
    slug: "indianoil-rbl-bank-xtra-credit-card-rbl-bank",
  },
  {
    name: "Bajaj Finserv RBL Bank SuperCard",
    bankName: "RBL Bank",
    category: "EMI",
    slug: "bajaj-finserv-rbl-bank-supercard-rbl-bank",
  },
  {
    name: "RBL Bank Movies & More Credit Card",
    bankName: "RBL Bank",
    category: "Entertainment",
    slug: "rbl-bank-movies-&-more-credit-card-rbl-bank",
  },
  {
    name: "RBL Bank Titanium Delight Credit Card",
    bankName: "RBL Bank",
    category: "Rewards",
    slug: "rbl-bank-titanium-delight-credit-card-rbl-bank",
  },
  {
    name: "American Express Platinum Card",
    bankName: "American Express",
    category: "Ultra Premium",
    slug: "american-express-platinum-card-american-express",
  },
  {
    name: "American Express Platinum Reserve Credit Card",
    bankName: "American Express",
    category: "Premium",
    slug: "american-express-platinum-reserve-credit-card-american-express",
  },
  {
    name: "American Express Platinum Travel Credit Card",
    bankName: "American Express",
    category: "Travel",
    slug: "american-express-platinum-travel-credit-card-american-express",
  },
  {
    name: "American Express Membership Rewards Credit Card",
    bankName: "American Express",
    category: "Rewards",
    slug: "american-express-membership-rewards-credit-card-american-express",
  },
  {
    name: "American Express Gold Card",
    bankName: "American Express",
    category: "Charge Card",
    slug: "american-express-gold-card-american-express",
  },
  {
    name: "American Express SmartEarn Credit Card",
    bankName: "American Express",
    category: "Cashback",
    slug: "american-express-smartearn-credit-card-american-express",
  },
  {
    name: "YES Bank MARQUEE Credit Card",
    bankName: "YES Bank",
    category: "Ultra Premium",
    slug: "yes-bank-marquee-credit-card-yes-bank",
  },
  {
    name: "YES Bank RESERVE Credit Card",
    bankName: "YES Bank",
    category: "Ultra Premium",
    slug: "yes-bank-reserve-credit-card-yes-bank",
  },
  {
    name: "YES Bank ELITE+ Credit Card",
    bankName: "YES Bank",
    category: "Premium",
    slug: "yes-bank-elite+-credit-card-yes-bank",
  },
  {
    name: "YES Bank SELECT Credit Card",
    bankName: "YES Bank",
    category: "Mid-range",
    slug: "yes-bank-select-credit-card-yes-bank",
  },
  {
    name: "YES Bank ACE Credit Card",
    bankName: "YES Bank",
    category: "Entry-level",
    slug: "yes-bank-ace-credit-card-yes-bank",
  },
  {
    name: "YES Bank WELLNESS PLUS Credit Card",
    bankName: "YES Bank",
    category: "Wellness",
    slug: "yes-bank-wellness-plus-credit-card-yes-bank",
  },
  {
    name: "Etihad Guest SBI Card",
    bankName: "SBI Card",
    category: "Airline",
    slug: "etihad-guest-sbi-card-sbi-card",
  },
  {
    name: "Vistara SBI Card PRIME",
    bankName: "SBI Card",
    category: "Airline",
    slug: "vistara-sbi-card-prime-sbi-card",
  },
  {
    name: "Vistara SBI Card",
    bankName: "SBI Card",
    category: "Airline",
    slug: "vistara-sbi-card-sbi-card",
  },
  {
    name: "IRCTC SBI Card Premier",
    bankName: "SBI Card",
    category: "Travel",
    slug: "irctc-sbi-card-premier-sbi-card",
  },
  {
    name: "IRCTC SBI Platinum Card",
    bankName: "SBI Card",
    category: "Travel",
    slug: "irctc-sbi-platinum-card-sbi-card",
  },
  {
    name: "Club Vistara SBI Card PRIME",
    bankName: "SBI Card",
    category: "Airline",
    slug: "club-vistara-sbi-card-prime-sbi-card",
  },
  {
    name: "Club Vistara SBI Card",
    bankName: "SBI Card",
    category: "Airline",
    slug: "club-vistara-sbi-card-sbi-card",
  },
  {
    name: "Yatra SBI Card",
    bankName: "SBI Card",
    category: "Travel",
    slug: "yatra-sbi-card-sbi-card",
  },
  {
    name: "Apollo SBI Credit Card",
    bankName: "SBI Card",
    category: "Healthcare",
    slug: "apollo-sbi-credit-card-sbi-card",
  },
  {
    name: "Cashback SBI Card",
    bankName: "SBI Card",
    category: "Cashback",
    slug: "cashback-sbi-card-sbi-card",
  },
  {
    name: "SBI Unnati Credit Card",
    bankName: "SBI Card",
    category: "Secured",
    slug: "sbi-unnati-credit-card-sbi-card",
  },
  {
    name: "OLA Money SBI Card",
    bankName: "SBI Card",
    category: "Digital",
    slug: "ola-money-sbi-card-sbi-card",
  },
  {
    name: "Paytm SBI Card",
    bankName: "SBI Card",
    category: "Digital",
    slug: "paytm-sbi-card-sbi-card",
  },
  {
    name: "Paytm SBI Card Select",
    bankName: "SBI Card",
    category: "Digital",
    slug: "paytm-sbi-card-select-sbi-card",
  },
  {
    name: "IndusInd Bank Legend Credit Card",
    bankName: "IndusInd Bank",
    category: "Premium",
    slug: "indusind-bank-legend-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Platinum Aura Edge Credit Card",
    bankName: "IndusInd Bank",
    category: "Premium",
    slug: "indusind-platinum-aura-edge-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Bank Platinum Credit Card",
    bankName: "IndusInd Bank",
    category: "Entry-level",
    slug: "indusind-bank-platinum-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Avios Visa Infinite Credit Card",
    bankName: "IndusInd Bank",
    category: "Airline",
    slug: "indusind-avios-visa-infinite-credit-card-indusind-bank",
  },
  {
    name: "EazyDiner IndusInd Bank Signature Credit Card",
    bankName: "IndusInd Bank",
    category: "Dining",
    slug: "eazydiner-indusind-bank-signature-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Tiger Credit Card",
    bankName: "IndusInd Bank",
    category: "Lifestyle",
    slug: "indusind-tiger-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Bank Duo Credit Card",
    bankName: "IndusInd Bank",
    category: "Co-branded",
    slug: "indusind-bank-duo-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Celesta Credit Card",
    bankName: "IndusInd Bank",
    category: "Premium",
    slug: "indusind-celesta-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Crest Credit Card",
    bankName: "IndusInd Bank",
    category: "Premium",
    slug: "indusind-crest-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Nexxt Credit Card",
    bankName: "IndusInd Bank",
    category: "Rewards",
    slug: "indusind-nexxt-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Bank Platinum RuPay Credit Card",
    bankName: "IndusInd Bank",
    category: "UPI",
    slug: "indusind-bank-platinum-rupay-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Bank Samman RuPay Credit Card",
    bankName: "IndusInd Bank",
    category: "Secured",
    slug: "indusind-bank-samman-rupay-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Bank Indulge Credit Card",
    bankName: "IndusInd Bank",
    category: "Ultra Premium",
    slug: "indusind-bank-indulge-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Bank Pioneer Heritage Credit Card",
    bankName: "IndusInd Bank",
    category: "Ultra Premium",
    slug: "indusind-bank-pioneer-heritage-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Bank Pioneer Legacy Credit Card",
    bankName: "IndusInd Bank",
    category: "Ultra Premium",
    slug: "indusind-bank-pioneer-legacy-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Bank Pioneer Private Credit Card",
    bankName: "IndusInd Bank",
    category: "Ultra Premium",
    slug: "indusind-bank-pioneer-private-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Solitaire Credit Card",
    bankName: "IndusInd Bank",
    category: "Ultra Premium",
    slug: "indusind-solitaire-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Pinnacle World Credit Card",
    bankName: "IndusInd Bank",
    category: "Ultra Premium",
    slug: "indusind-pinnacle-world-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Bank ePay Amex Credit Card",
    bankName: "IndusInd Bank",
    category: "Business",
    slug: "indusind-bank-epay-amex-credit-card-indusind-bank",
  },
  {
    name: "IndusInd Bank Club Vistara Explorer Credit Card",
    bankName: "IndusInd Bank",
    category: "Airline",
    slug: "indusind-bank-club-vistara-explorer-credit-card-indusind-bank",
  },
  {
    name: "IDFC FIRST Millennia Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Rewards",
    slug: "idfc-first-millennia-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST Classic Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Entry-level",
    slug: "idfc-first-classic-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST Select Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Mid-range",
    slug: "idfc-first-select-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST Wealth Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Premium",
    slug: "idfc-first-wealth-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST WoW Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Secured",
    slug: "idfc-first-wow-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST Power+ (HPCL) Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Fuel",
    slug: "idfc-first-power+-(hpcl)-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST Swyp EMI Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "EMI",
    slug: "idfc-first-swyp-emi-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST WOW Secured Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Secured",
    slug: "idfc-first-wow-secured-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST Private Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Ultra Premium",
    slug: "idfc-first-private-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST WOW RuPay Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "UPI",
    slug: "idfc-first-wow-rupay-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST Vistara Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Airline",
    slug: "idfc-first-vistara-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST Ashva Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Lifestyle",
    slug: "idfc-first-ashva-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST Mayura Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Lifestyle",
    slug: "idfc-first-mayura-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST Indigo Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Airline",
    slug: "idfc-first-indigo-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST HPCL First Power Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Fuel",
    slug: "idfc-first-hpcl-first-power-credit-card-idfc-first-bank",
  },
  {
    name: "IDFC FIRST HPCL Power+ Credit Card",
    bankName: "IDFC FIRST Bank",
    category: "Fuel",
    slug: "idfc-first-hpcl-power+-credit-card-idfc-first-bank",
  },
  {
    name: "Ferrari Signature Credit Card",
    bankName: "ICICI Bank",
    category: "Lifestyle",
    slug: "ferrari-signature-credit-card-icici-bank",
  },
  {
    name: "Ferrari Platinum Credit Card",
    bankName: "ICICI Bank",
    category: "Lifestyle",
    slug: "ferrari-platinum-credit-card-icici-bank",
  },
  {
    name: "Axis Bank Magnus Credit Card",
    bankName: "Axis Bank",
    category: "Ultra Premium",
    slug: "axis-bank-magnus-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Reserve Credit Card",
    bankName: "Axis Bank",
    category: "Ultra Premium",
    slug: "axis-bank-reserve-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Burgundy Private Credit Card",
    bankName: "Axis Bank",
    category: "Ultra Premium",
    slug: "axis-bank-burgundy-private-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Select Credit Card",
    bankName: "Axis Bank",
    category: "Premium",
    slug: "axis-bank-select-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Privilege Credit Card",
    bankName: "Axis Bank",
    category: "Mid-range",
    slug: "axis-bank-privilege-credit-card-axis-bank",
  },
  {
    name: "Axis Bank My Zone Credit Card",
    bankName: "Axis Bank",
    category: "Lifestyle",
    slug: "axis-bank-my-zone-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Neo Credit Card",
    bankName: "Axis Bank",
    category: "Entry-level",
    slug: "axis-bank-neo-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Flipkart Credit Card",
    bankName: "Axis Bank",
    category: "Cashback",
    slug: "axis-bank-flipkart-credit-card-axis-bank",
  },
  {
    name: "Airtel Axis Bank Credit Card",
    bankName: "Axis Bank",
    category: "Cashback",
    slug: "airtel-axis-bank-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Ace Credit Card",
    bankName: "Axis Bank",
    category: "Cashback",
    slug: "axis-bank-ace-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Freecharge Credit Card",
    bankName: "Axis Bank",
    category: "Digital",
    slug: "axis-bank-freecharge-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Freecharge Plus Credit Card",
    bankName: "Axis Bank",
    category: "Digital",
    slug: "axis-bank-freecharge-plus-credit-card-axis-bank",
  },
  {
    name: "Axis Bank IOCL Credit Card",
    bankName: "Axis Bank",
    category: "Fuel",
    slug: "axis-bank-iocl-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Atlas Credit Card",
    bankName: "Axis Bank",
    category: "Travel",
    slug: "axis-bank-atlas-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Vistara Infinite Credit Card",
    bankName: "Axis Bank",
    category: "Airline",
    slug: "axis-bank-vistara-infinite-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Vistara Signature Credit Card",
    bankName: "Axis Bank",
    category: "Airline",
    slug: "axis-bank-vistara-signature-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Vistara Platinum Credit Card",
    bankName: "Axis Bank",
    category: "Airline",
    slug: "axis-bank-vistara-platinum-credit-card-axis-bank",
  },
  {
    name: "Axis Bank SpiceJet Credit Card",
    bankName: "Axis Bank",
    category: "Airline",
    slug: "axis-bank-spicejet-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Air India Signature Credit Card",
    bankName: "Axis Bank",
    category: "Airline",
    slug: "axis-bank-air-india-signature-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Air India Platinum Credit Card",
    bankName: "Axis Bank",
    category: "Airline",
    slug: "axis-bank-air-india-platinum-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Miles & More Select Credit Card",
    bankName: "Axis Bank",
    category: "Airline",
    slug: "axis-bank-miles-&-more-select-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Miles & More World Credit Card",
    bankName: "Axis Bank",
    category: "Airline",
    slug: "axis-bank-miles-&-more-world-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Samsung Infinite Credit Card",
    bankName: "Axis Bank",
    category: "Co-branded",
    slug: "axis-bank-samsung-infinite-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Samsung Signature Credit Card",
    bankName: "Axis Bank",
    category: "Co-branded",
    slug: "axis-bank-samsung-signature-credit-card-axis-bank",
  },
  {
    name: "Axis Bank IndianOil Credit Card",
    bankName: "Axis Bank",
    category: "Fuel",
    slug: "axis-bank-indianoil-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Club Vistara Credit Card Series",
    bankName: "Axis Bank",
    category: "Airline",
    slug: "axis-bank-club-vistara-credit-card-series-axis-bank",
  },
  {
    name: "Axis Bank Insta Easy Credit Card",
    bankName: "Axis Bank",
    category: "Secured",
    slug: "axis-bank-insta-easy-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Platinum Credit Card",
    bankName: "Axis Bank",
    category: "Entry-level",
    slug: "axis-bank-platinum-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Rewards Credit Card",
    bankName: "Axis Bank",
    category: "Rewards",
    slug: "axis-bank-rewards-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Buzz Credit Card",
    bankName: "Axis Bank",
    category: "Lifestyle",
    slug: "axis-bank-buzz-credit-card-axis-bank",
  },
  {
    name: "Axis Bank AURA Credit Card",
    bankName: "Axis Bank",
    category: "Wellness",
    slug: "axis-bank-aura-credit-card-axis-bank",
  },
  {
    name: "Axis Bank Nike Credit Card",
    bankName: "Axis Bank",
    category: "Legacy",
    slug: "axis-bank-nike-credit-card-axis-bank",
  },
  {
    name: "SBI Card ELITE",
    bankName: "SBI Card",
    category: "Premium",
    slug: "sbi-card-elite-sbi-card",
  },
  {
    name: "SBI Card PRIME",
    bankName: "SBI Card",
    category: "Premium",
    slug: "sbi-card-prime-sbi-card",
  },
  {
    name: "SBI AURUM Credit Card",
    bankName: "SBI Card",
    category: "Ultra Premium",
    slug: "sbi-aurum-credit-card-sbi-card",
  },
  {
    name: "SBI Card PULSE",
    bankName: "SBI Card",
    category: "Lifestyle",
    slug: "sbi-card-pulse-sbi-card",
  },
  {
    name: "SimplyCLICK SBI Card",
    bankName: "SBI Card",
    category: "Rewards",
    slug: "simplyclick-sbi-card-sbi-card",
  },
  {
    name: "SimplySAVE SBI Card",
    bankName: "SBI Card",
    category: "Rewards",
    slug: "simplysave-sbi-card-sbi-card",
  },
  {
    name: "SimplyCLICK Advantage SBI Card",
    bankName: "SBI Card",
    category: "Rewards",
    slug: "simplyclick-advantage-sbi-card-sbi-card",
  },
  {
    name: "SimplySAVE Advantage SBI Card",
    bankName: "SBI Card",
    category: "Rewards",
    slug: "simplysave-advantage-sbi-card-sbi-card",
  },
  {
    name: "SBI Advantage Plus Credit Card",
    bankName: "SBI Card",
    category: "Mid-range",
    slug: "sbi-advantage-plus-credit-card-sbi-card",
  },
  {
    name: "SBI Advantage Platinum Credit Card",
    bankName: "SBI Card",
    category: "Mid-range",
    slug: "sbi-advantage-platinum-credit-card-sbi-card",
  },
  {
    name: "SBI Platinum Credit Card",
    bankName: "SBI Card",
    category: "Entry-level",
    slug: "sbi-platinum-credit-card-sbi-card",
  },
  {
    name: "BPCL SBI Card Octane",
    bankName: "SBI Card",
    category: "Fuel",
    slug: "bpcl-sbi-card-octane-sbi-card",
  },
  {
    name: "BPCL SBI Card",
    bankName: "SBI Card",
    category: "Fuel",
    slug: "bpcl-sbi-card-sbi-card",
  },
  {
    name: "Air India SBI Signature Card",
    bankName: "SBI Card",
    category: "Airline",
    slug: "air-india-sbi-signature-card-sbi-card",
  },
  {
    name: "Air India SBI Platinum Card",
    bankName: "SBI Card",
    category: "Airline",
    slug: "air-india-sbi-platinum-card-sbi-card",
  },
  {
    name: "Etihad Guest SBI Premier Card",
    bankName: "SBI Card",
    category: "Airline",
    slug: "etihad-guest-sbi-premier-card-sbi-card",
  },
];
