export const ROUTES = {
  CARD_FORM: "/info",
  CARD_RECOMMENDATIOMS: "/recommendations",
  HOME: "/",
  ABOUT: "/about",
  CHAT: "/chat",
  SIGN_UP: "/sign-up",
  SIGN_IN: "/sign-in",
  VERIFY_EMAIL: "/verify",
  SAVING_CALCULATOR: "/tools/saving-calculator",
  CHANGE_PASSWORD: "/change-password",
  LOGGED_IN_HOME: "/home",
  PROFILE: "/profile",
  FAVORITES: "/favourites",
  DASHBOARD: "/home",
  LOGOUT: "/logout",
  PRIVACY_POLICY: "privacy-policy",
  COMPLIANCE: "/legal-compliance",
  TERMS: "/terms",
  AFFILIATE_DISCLOSURE: "/affiliate-disclosure",
  CHOOSE_CARD: "/choose-card",
  APPLY_CARD: "/apply-card",
  SPEND_OPTIMIZER: "/spend-optimizer",
  POINTS_REDEMPTION: "/redemption",
  SUPPORT: "support",
  USER_INFO: "/user-info",
  CARD_VALUE_CALCULATOR: "/card-value-calculator",
  INSIGHTS: "/insights",
};

export const PUBLIC_ROUTES = [
  "/about",
  "/sign-in",
  "/verify",
  "/tools/saving-calculator",
  "/card-value-calculator",
  "/change-password",
  "/privacy-policy",
  "/legal-compliance",
  "/terms",
  "/affiliate-disclosure",
  "/",
  "/chat",
  "/landing",
  "/choose-card",
  "/user-info",
  "/sale/flipkart",
];
