// Define all event names
export enum EventName {
  LANDING_PAGE = "LANDING_PAGE",
  BUTTON_CLICKED = "BUTTON_CLICKED",
  WAITLIST_GET_EARLY_ACCESS_BTN = "WAITLIST_GET_EARLY_ACCESS_BTN",
  CLOSE_WAITLIST_MODEL_BTN = "CLOSE_WAITLIST_MODEL_BTN",
  JOIN_WAITLIST_BTN = "JOIN_WAITLIST_BTN",
  STEP_INTO_SMARTER_SPENDING_BTN = "STEP_INTO_SMARTER_SPENDING_BTN",
  CHECK_MY_CARD_NOW_BTN = "CHECK_MY_CARD_NOW_BTN",
  ANALYSE_FOR_BEST_VALUE_BTN = "ANALYSE_FOR_BEST_VALUE_BTN",
  RECOMMEND_MY_BEST_CARD_BTN = "RECOMMEND_MY_BEST_CARD_BTN",
}
